
---
# see here: https://docs.ansible.com/ansible/latest/modules/dnf_module.html

- hosts: 127.0.0.1
  tasks:

  - name: installing gedit
    dnf:
      name: gedit
      state: present

  - name: install apache
    dnf:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started
#      state: stopped
#      enabled: yes/no
...
